name: pny_driver
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0+14
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  dio: ^5.3.2
  provider: ^6.0.4
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  lottie: ^2.0.0
  location_geocoder: ^1.0.5
  either_dart: ^1.0.0
  http: ^0.13.5
  camera: ^0.10.0+4
  hand_signature: ^3.0.2
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  geolocator: ^10.0.0
  flutter_polyline_points: ^1.0.0
  geocoder2: ^1.4.0
  url_launcher: ^6.1.7
  slide_to_act: ^2.0.1
  flutter_background: ^1.1.0
  brasil_fields: ^1.8.0
  flutter_native_splash: ^2.2.16
  animated_splash_screen: ^1.3.0
  date_format: ^2.0.7
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
