name: pny_driver
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  dio: ^4.0.6
  provider: ^6.0.4
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  lottie: ^2.0.0
  location_geocoder: ^1.0.5
  either_dart: ^0.3.0
  http: ^0.13.5
  camera: ^0.10.0+4
  hand_signature: ^2.3.0+1
  intl: ^0.17.0
  flutter_staggered_animations: ^1.1.1
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  geocoder2: ^1.4.0
  url_launcher: ^6.1.7
  slide_to_act: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
